extern const GeoLayout breakable_box_no_shadow_geo[];
extern const GeoLayout breakable_box_geo[];
extern u8 breakable_box_lantern_ci8[];
extern u8 breakable_box_lantern_pal_rgba16[];
extern Vtx breakable_box_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx breakable_box_Cube_mesh_layer_1_vtx_0[24];
extern Gfx breakable_box_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_breakable_box_f3dlite_material[];
extern Gfx mat_revert_breakable_box_f3dlite_material[];
extern Gfx breakable_box_Cube_mesh_layer_1[];
